//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Firma_transportowaEntities5 : DbContext
    {
        public Firma_transportowaEntities5()
            : base("name=Firma_transportowaEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pracownicy> pracownicy { get; set; }
        public virtual DbSet<pracownicy_kierowcy> pracownicy_kierowcy { get; set; }
        public virtual DbSet<samochody> samochody { get; set; }
        public virtual DbSet<zlecajacy> zlecajacy { get; set; }
        public virtual DbSet<zlecenia_kierowcy> zlecenia_kierowcy { get; set; }
    }
}
