//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class samochody
    {
        public int id_samochodu { get; set; }
        public string nr_rejestracyjny { get; set; }
        public string ladownosc { get; set; }
        public string wiek_pojazdu { get; set; }
    
        public virtual pracownicy_kierowcy pracownicy_kierowcy { get; set; }
    }
}
