//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zlecajacy
    {
        public int id_zlecajacego { get; set; }
        public string nazwa_firmy { get; set; }
        public Nullable<decimal> NIP { get; set; }
    
        public virtual zlecajacy zlecajacy1 { get; set; }
        public virtual zlecajacy zlecajacy2 { get; set; }
    }
}
