//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zlecajacy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zlecajacy()
        {
            this.zlecenia_kierowcy = new HashSet<zlecenia_kierowcy>();
        }
    
        public int id_zlecajacego { get; set; }
        public string nazwa_firmy { get; set; }
        public Nullable<decimal> NIP { get; set; }
    
        public virtual zlecajacy zlecajacy1 { get; set; }
        public virtual zlecajacy zlecajacy2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zlecenia_kierowcy> zlecenia_kierowcy { get; set; }
    }
}
