//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zlecenia_kierowcy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zlecenia_kierowcy()
        {
            this.pracownicy_kierowcy = new HashSet<pracownicy_kierowcy>();
        }
    
        public int id_zlecenia { get; set; }
        public Nullable<System.DateTime> czas_rozpoczecia { get; set; }
        public Nullable<System.DateTime> czas_zakonczenia { get; set; }
        public string waga_zlecenia { get; set; }
        public int id_zlecajacego { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pracownicy_kierowcy> pracownicy_kierowcy { get; set; }
        public virtual zlecajacy zlecajacy { get; set; }
    }
}
